_target_: src.datasets.stimulus_dataset.LabDataset
df_path: ${data_path}/${data_name}
meaningful_features:
  - RRI
  - BPM
  - SDNN
  - rMSSD
  - pNN50
  - VLF
  - LF
  - HF
  - VLFp
  - LFp
  - HFp
  - lnVLF
  - lnLF
  - lnHF
  - VLF/HF
  - LF/HF
  - tPow
  - dPow
  - dHz
  - pPow
  - pHz
  - CohRatio
  - RSA_PB
emotion: arousal
standard: compound
condition: normal
filter_outlier: True