# @package _global_
defaults:
  - dataset_module: stimulus_lab_dataset
  - architecture_module: basic_archimodule
  - hydra: hydra

project_dir: C:/Users/ddang/Desktop/projects/hrv-emotion

data_path: ${project_dir}/tabular_dataset
data_name: sl_thirty_augmented.xlsx
meaningful_features:
  - RRI
  - BPM
  - SDNN
  - rMSSD
  - pNN50
  - VLF
  - LF
  - HF
  - VLFp
  - LFp
  - HFp
  - lnVLF
  - lnLF
  - lnHF
  - VLF/HF
  - LF/HF
  - tPow
  - dPow
  - dHz
  - pPow
  - pHz
  - CohRatio
  - RSA_PB
condition: arousal
model_save_path: ${project_dir}/save_model/basic_classifier/all_features
result_path: ${project_dir}/result_reports

num_folds: 10
fold_seed: 2024
boosting_type: gbdt
objective: binary
metric: binary_logloss
result_name: basic_all_features_train_result.csv
plt_save_path: ${project_dir}/feature_importance/basic_all_features

run_name: basic_train
work_dir: ${hydra:runtime.cwd}