# @package _global_
defaults:
  - dataset_module: stimulus_lab_dataset
  - tuner_module: xgb_tunermodule
  - hydra: hydra

project_dir: C:/Users/ddang/Desktop/projects/hrv-emotion

dataset: sl_thirty_augmented
data_path: ${project_dir}/tabular_dataset
data_name: ${dataset}.xlsx
meaningful_features:
  - RRI
  - BPM
  - SDNN
  - rMSSD
  - pNN50
  - VLF
  - LF
  - HF
  - VLFp
  - LFp
  - HFp
  - lnVLF
  - lnLF
  - lnHF
  - VLF/HF
  - LF/HF
  - tPow
  - dPow
  - dHz
  - pPow
  - pHz
  - CohRatio
  - RSA_PB
condition: arousal

split_size: 0.2
num_folds: 10
metric: f1
num_trials: 100
seed: 2024
tuning_way: original
model_name: xgb
save_path: ${project_dir}/hparams/${condition}

project_name: XGBClassifier

run_name: ${tags}-tune
work_dir: ${hydra:runtime.cwd}

tags: ${project_name}-${dataset}-tuning_way_{tuning_way}-metric_{metric}-num_trials{num_trials}