# HYDRA_FULL_ERROR=1 python signal_to_hrv.py root_dataset=sl_rppg dataset=sl_rppg_60 sampling_rate=60 run_name=interpolated_signal_to_hrv
HYDRA_FULL_ERROR=1 python signal_to_hrv.py root_dataset=sl_rppg dataset=sl_rppg_120 sampling_rate=120 run_name=interpolated_signal_to_hrv
# HYDRA_FULL_ERROR=1 python signal_to_hrv.py root_dataset=sl_rppg dataset=sl_rppg_240 sampling_rate=240 run_name=interpolated_signal_to_hrv
HYDRA_FULL_ERROR=1 python signal_to_hrv.py root_dataset=sl_rppg dataset=sl_rppg_480 sampling_rate=480 run_name=interpolated_signal_to_hrv