HYDRA_FULL_ERROR=1 python signal_to_hrv.py dataset=sl_50 sampling_rate=50 run_name=undersampled_signal_to_hrv
HYDRA_FULL_ERROR=1 python signal_to_hrv.py dataset=sl_100 sampling_rate=100 run_name=undersampled_signal_to_hrv
HYDRA_FULL_ERROR=1 python signal_to_hrv.py dataset=sl_250 sampling_rate=250 run_name=undersampled_signal_to_hrv