maxima_peak_detection:
  _target_: src.signal_preprocess.maxima_peak_detection.MaximaPeakDetection
  threshold: 0
  detrend_factor: 1
  is_display: False

biopac_data_slicer:
  _target_: src.signal_preprocess.biopac_data_slicer.BioPacDataSlicer
  log_path: ${project_dir}/dataset/${dataset}/logs
  data_path: ${project_dir}/dataset/${dataset}/raw_datas
  save_path: ${project_dir}/dataset/${dataset}/signals