_target_: src.dataset_modules.stimulus_dataset.StimulusDataset
df_path: ${save_load_dir}/tabular_dataset/sl_thirty_augmented.xlsx
meaningful_features:
  - RRI
  - BPM
  - SDNN
  - rMSSD
  - pNN50
  - VLF
  - LF
  - HF
  - VLFp
  - LFp
  - HFp
  - lnVLF
  - lnLF
  - lnHF
  - VLF/HF
  - LF/HF
  - tPow
  - dPow
  - dHz
  - pPow
  - pHz
  - CohRatio
  - RSA_PB
emotion: arousal
standard: compound
condition: normal
filter_outlier: True